export const RECIPE_LIST_REQUEST = 'RECIPE_LIST_REQUEST';
export const RECIPE_LIST_SUCCESS = 'RECIPE_LIST_SUCCESS';
export const RECIPE_LIST_FAIL = 'RECIPE_LIST_FAIL';

export const RECIPE_SAVE_REQUEST = 'RECIPE_SAVE_REQUEST';
export const RECIPE_SAVE_SUCCESS = 'RECIPE_SAVE_SUCCESS';
export const RECIPE_SAVE_FAIL = 'RECIPE_SAVE_FAIL';

export const RECIPE_DELETE_REQUEST = 'RECIPE_DELETE_REQUEST';
export const RECIPE_DELETE_SUCCESS = 'RECIPE_DELETE_SUCCESS';
export const RECIPE_DELETE_FAIL = 'RECIPE_DELETE_FAIL';

export const RECIPE_FILTER_REQUEST = 'RECIPE_FILTER_REQUEST';
export const RECIPE_FILTER_SUCCESS = 'RECIPE_FILTER_SUCCESS';
export const RECIPE_FILTER_FAIL = 'RECIPE_FILTER_FAIL';